export type ChangelogTrack = "web" | "cli" | "sdk" | "mcp";

export interface ChangelogEntry {
  version: string;
  date: string;
  title: string;
  track: ChangelogTrack;
  items: string[];
}

export const TRACK_LABELS: Record<ChangelogTrack, string> = {
  web: "Web App",
  cli: "CLI",
  sdk: "SDK",
  mcp: "MCP",
};

export const APP_VERSION = "0.29.0";
export const CLI_VERSION = "1.1.3";
export const SDK_VERSION = "1.9.0";
export const MCP_VERSION = "1.7.0";

export const CHANGELOG: ChangelogEntry[] = [
  // ─── Web App ────────────────────────────────────────────────────────
  {
    version: "0.29.0",
    date: "2026-08-21",
    title: "Sign In with Email and Password",
    track: "web",
    items: [
      "Create an account with an email address and password, alongside GitHub and Google: sign-up sends a confirmation link, and the account is usable once the email is verified",
      "Forgot password? Request a reset link from the login page and choose a new password on the reset page; the link works in any browser",
      "Team invitees without a GitHub or Google account can now sign up with the invited email address and the invite is waiting for them",
      "OAuth errors and invalid email links now show a message on the login page instead of being dropped",
    ],
  },
  {
    version: "0.28.1",
    date: "2026-08-21",
    title: "Fix: Team Checkout for Owners Who Already Have a Polar Customer",
    track: "web",
    items: [
      "Team checkout no longer fails for owners who already have a personal Pro subscription (or own another team): the team's Polar customer is now created as a team customer with the owner as its owner member, instead of a second customer on the owner's email, which Polar rejects",
      "Team billing errors now reach the browser with their detail instead of being swallowed by Cloudflare's 502 page",
      "Polar errors are logged without the request's authorization header",
    ],
  },
  {
    version: "0.28.0",
    date: "2026-08-19",
    title: "Invite Anyone to Your Team by Email",
    track: "web",
    items: [
      "Team invites no longer require the invitee to have an account: invite any email address, they get an invite email, and signing up with that address links the invite to their new account automatically",
      "Invite emails tell the invitee who invited them, to which team, and where to accept",
      "Clicking Subscribe again within 30 minutes reuses the open checkout session for the same seat count instead of creating a second one, and the billing webhook ignores events from a subscription the team doesn't hold",
      "Pro renewals now reset the monthly request counter the moment the renewal lands instead of relying on a background sweep",
      "When a member leaves or is removed, the endpoints they shared with the team are unshared so their traffic stops drawing from the team pool",
      "Checkout failures now surface Polar's validation detail (e.g. a rejected billing email) instead of a bare error",
    ],
  },
  {
    version: "0.27.0",
    date: "2026-08-18",
    title: "Teams Is Now Its Own Seat-Based Plan",
    track: "web",
    items: [
      "Teams no longer requires Pro — any account can create a team, and the team carries its own subscription at $12/seat/mo",
      "Every seat adds 100,000 requests per 30 days to a pool shared by the whole team: requests on team-shared endpoints bill the team instead of the endpoint owner",
      "Seats are the member cap — add a seat to add a member, and freed seats are reusable",
      "Team-billed requests are kept for 31 days regardless of the endpoint owner's plan",
      "Per-team billing through Polar: subscribe, adjust seats, cancel, and resubscribe from the team page",
      "A team without an active subscription is suspended — its data is kept, but invites, sharing, and member access to shared endpoints pause until it subscribes",
    ],
  },
  {
    version: "0.26.3",
    date: "2026-08-11",
    title: "Security: dependency updates across the stack",
    track: "web",
    items: [
      "Next.js 16.2.11, patching several security advisories in the framework",
      "All open Dependabot security alerts resolved: hardened transitive dependencies (sharp, tar, js-yaml, dompurify, hono, and friends) via lockfile overrides",
      "Routine dependency refresh: React 19.2.8, Supabase SSR, Radix UI, Polar SDK, PostHog, and the Rust receiver/CLI dependency set (including a quinn-proto advisory fix)",
    ],
  },
  {
    version: "0.26.2",
    date: "2026-08-11",
    title: "Fix: CLI login no longer locks out at the API key cap",
    track: "web",
    items: [
      "CLI device logins at the 10-key limit now rotate the oldest CLI-issued key instead of failing with an opaque “Claim failed” — manually created keys are never touched",
      "When a claim does hit the cap (all keys manually created), the CLI now shows an actionable message pointing to the account page instead of “Claim failed”",
    ],
  },
  {
    version: "0.26.1",
    date: "2026-07-17",
    title: "Fix: stale delete button in endpoint settings",
    track: "web",
    items: [
      "Fixed the endpoint settings dialog showing a disabled “Deleting...” button when opening another endpoint's settings right after deleting one — previously only a page reload cleared it",
    ],
  },
  {
    version: "0.26.0",
    date: "2026-07-07",
    title: "The Landing Page Is Now the Dashboard",
    track: "web",
    items: [
      "Visit webhooks.cc and you're in the inspector: a live guest webhook URL is created the moment you arrive — no signup — with the full request dashboard (live feed, body tree, headers, replay) filling the first screen",
      "One-click test sends from the empty state: a custom payload or signed Stripe, GitHub, and Shopify templates, plus a copy-able curl command",
      "One click with GitHub or Google keeps your guest endpoint and unlocks the free plan — messaging now spells this out at every step, including a guest-vs-free comparison",
      "/go retired: it permanently redirects to the landing page, which now provides the same experience",
      "Crawler protection: guest endpoints are no longer created for bots (server-side user-agent screen + creation waits for a human input signal)",
      "SEO: HowTo structured data, new FAQ entries, and an instant-URL page title and description",
    ],
  },
  {
    version: "0.25.0",
    date: "2026-06-12",
    title: "Landing Redesign + Per-Provider Webhook Pages",
    track: "web",
    items: [
      "New provider pages at /webhooks — setup steps, signature details, and sample events for all 32 supported providers, plus a browsable hub grouped by category",
      "Landing page redesigned around a sign-up-first hero: prominent GitHub/Google start-free buttons, with the no-signup guest endpoint as the secondary path",
      "New provider strip and navbar links (Docs, Providers, Compare, Pricing, Blog) for easier discovery",
      "SEO: provider pages added to the sitemap, /agent/claim marked noindex",
    ],
  },
  {
    version: "0.24.0",
    date: "2026-06-05",
    title: "4 New Providers — DocuSign, Adyen, PayPal, Plaid",
    track: "web",
    items: [
      "Provider catalog grows from 28 to 32: added DocuSign, Adyen, PayPal, and Plaid across templates and detection",
      "Server-side signature verification now supports DocuSign HMAC, Adyen body-embedded HMAC, and PayPal RSA certificate verification; Plaid remains template-only until Plaid JWT/JWK credentials are supported",
      "Endpoint settings and the Signature tab use provider-specific credential labels, including PayPal Webhook ID and Adyen HMAC Key",
    ],
  },
  {
    version: "0.23.1",
    date: "2026-06-02",
    title: "Fix: send-webhook templates for newer providers",
    track: "web",
    items: [
      'Fixed the dashboard send-webhook dialog failing with “Unsupported template "custom"” for 14 providers (HubSpot, Square, Meta, Lemon Squeezy, Coinbase Commerce, Razorpay, Cal.com, Intercom, Telegram, Mailgun, Calendly, Mux, Sentry, Bitbucket) — their template presets now derive from the SDK provider metadata so every listed provider can send a signed test webhook',
    ],
  },
  {
    version: "0.23.0",
    date: "2026-06-02",
    title: "Agent Registration — sandbox, claim codes, SMTP email",
    track: "web",
    items: [
      "Unclaimed agent credentials now work immediately in a bounded sandbox: an anonymous key can create ephemeral endpoints and read only its own captured requests, with strict cross-tenant isolation, before a human claims it",
      "Anonymous registrations get a short human-friendly claim code (e.g. ABCD-EFGH) alongside the claim link — a signed-in user can claim by typing the code at /agent/claim",
      "Verification emails (OTP) now send over SMTP in production (SMTP → Resend → dev fallback); local dev and tests keep using the in-process capture transport",
      "Documented the ID-JAG trusted-provider config format and added an identity-provider onboarding section to the hosted /auth.md",
    ],
  },
  {
    version: "0.22.0",
    date: "2026-06-01",
    title: "Agent Registration — auth.md (anonymous, verified email, ID-JAG)",
    track: "web",
    items: [
      "Implements the WorkOS auth.md agent-registration protocol: agents self-register a credential anonymously, via a verified-email one-time code, or by presenting a provider-signed ID-JAG identity assertion",
      "Adds RFC 9728 discovery (/.well-known/oauth-protected-resource and /.well-known/oauth-authorization-server), a hosted /auth.md, and a WWW-Authenticate hint on 401s so agents can discover how to authenticate",
      "Anonymous credentials can be claimed by a signed-in user from an in-app claim page, permanently attaching the key to their account",
      "Supports provider-driven revocation (logout token) for ID-JAG-issued credentials",
    ],
  },
  {
    version: "0.21.0",
    date: "2026-05-31",
    title: "7 New Providers — Square, HubSpot, Mailgun, Calendly, Mux, Sentry, Bitbucket",
    track: "web",
    items: [
      "Provider catalog grows from 21 to 28: added Square, HubSpot, Mailgun, Calendly, Mux, Sentry, and Bitbucket across templates, auto-detection, and signature verification",
      "Three new signing schemes are now supported server-side: URL + body (Square), HTTP method + URI + body + timestamp (HubSpot), and body-embedded signature fields (Mailgun)",
      "Endpoint settings, the send-webhook dialog, and the Signature tab list all 28 named providers; automatic server-side verification works for every one except SendGrid (IP allowlisting)",
      "Refreshed provider template and signature-verification docs with payload shapes, headers, and algorithms for each new provider",
    ],
  },
  {
    version: "0.20.4",
    date: "2026-05-31",
    title:
      "7 New Providers — Meta, Lemon Squeezy, Coinbase Commerce, Razorpay, Cal.com, Intercom, Telegram",
    track: "web",
    items: [
      "Provider catalog grows from 14 to 21: added Meta (WhatsApp/Messenger/Instagram), Lemon Squeezy, Coinbase Commerce, Razorpay, Cal.com, Intercom, and Telegram across templates, auto-detection, and signature verification",
      "Endpoint settings, the send-webhook dialog, and the Signature tab now list all new providers; server-side automatic verification works for every one",
      "Refreshed provider template and signature-verification docs with payload shapes, headers, and algorithms for each new provider",
    ],
  },
  {
    version: "0.20.3",
    date: "2026-05-24",
    title: "CLI v1.1.2 Release",
    track: "web",
    items: [
      "Ships the CLI v1.1.2 polish — correct version display in `whk update` and a clear, actionable message when the install directory isn't writable",
    ],
  },
  {
    version: "0.20.2",
    date: "2026-05-23",
    title: "MCP v1.4.1 & CLI v1.1.1 Release",
    track: "web",
    items: [
      "MCP and CLI version bumps ship transitive dependency upgrades — zod 4 in MCP, tokio 1.52 and rustls-webpki refresh in the CLI",
    ],
  },
  {
    version: "0.20.1",
    date: "2026-05-15",
    title: "CI hardening & lint cleanup",
    track: "web",
    items: [
      "CI: Build Web App job now uses placeholder env values when Supabase secrets aren't available (e.g. Dependabot PRs), so dependency-update PRs get a meaningful build signal",
      "Resolved new strict react-hooks lint errors surfaced by an upcoming plugin bump, keeping the workspace lint-clean across plugin versions",
    ],
  },
  {
    version: "0.20.0",
    date: "2026-05-15",
    title: "Provider Auto-Detect & Typeform Support",
    track: "web",
    items: [
      "Dashboard auto-detects the webhook provider from headers and payload and renders a colored provider badge on each request",
      "Provider icons (Stripe, GitHub, Shopify, Twilio, Slack, Paddle, Linear, Clerk, Discord, Vercel, GitLab, Typeform, and more) across the request list and detail panes",
      "Typeform added to provider templates and signature verification — configure on any endpoint",
      "Hardened signing configuration invariants: partial or stale provider state is no longer possible, eliminating a class of silent verification failures",
      "Refreshed provider docs, ngrok and webhook.site comparison guides, signature verification guide, and MCP tools reference",
    ],
  },
  {
    version: "0.19.1",
    date: "2026-04-16",
    title: "Guest Dashboard SEO Overhaul",
    track: "web",
    items: [
      "Fixed layout bug on /go where hero copy rendered above the navbar",
      "Added feature cards flanking the Send Your First Webhook widget — mock responses, signature verification, CLI tunnel, SDK testing, MCP, and search/replay — visible without scrolling on xl+ screens",
      "Expanded server-rendered SEO content (14 internal doc links, 12 headings, 751 words, BreadcrumbList + FAQPage schemas, hreflang alternates)",
      "Promoted the page h1 to a visible subtitle inside the nav on md+ screens",
    ],
  },
  {
    version: "0.19.0",
    date: "2026-04-14",
    title: "Signature Verification",
    track: "web",
    items: [
      "Server-side webhook signature verification for 13 providers — configure once per endpoint, every request verified automatically",
      "New Signature tab in request detail: paste a secret for instant client-side verification, or view stored server-side results with detailed error diagnostics",
      "Verification badges (shield icons) in the request list and summary bar for at-a-glance valid/invalid status",
      "Signing configuration section in endpoint settings: provider dropdown, encrypted secret storage, provider-specific tips",
      "SDK: matchVerified() and matchUnverified() matchers for test assertions",
      "MCP: verify_signature returns stored results without needing a secret; create/update endpoints with signing config",
      "CLI: X-Signature-Verified headers on tunnel, verification status in listen output, --signing-provider/--signing-secret on create",
    ],
  },
  {
    version: "0.18.3",
    date: "2026-04-11",
    title: "Blog Resilience & Housekeeping",
    track: "web",
    items: [
      "Blog pages gracefully fall back when Supabase is unreachable instead of erroring",
      "Added SECURITY.md and CODE_OF_CONDUCT.md for open-source governance",
    ],
  },
  {
    version: "0.18.2",
    date: "2026-04-10",
    title: "SDK v1.3.0 & MCP v1.2.0 Release",
    track: "web",
    items: [
      "Updated llms.txt and llms-full.txt with conditional response rules documentation",
      "SDK and MCP version bumps for response rules and provider consolidation",
    ],
  },
  {
    version: "0.18.1",
    date: "2026-04-10",
    title: "Blog Page Redesign",
    track: "web",
    items: [
      "Redesigned blog index with clear visual hierarchy: featured post, two latest cards, and a scannable list for all posts",
      "Compact page header replacing the bulky hero section",
      "Fixed blog posts not appearing after publish due to stale Next.js fetch cache",
    ],
  },
  {
    version: "0.18.0",
    date: "2026-04-10",
    title: "Conditional Response Rules",
    track: "web",
    items: [
      "Define ordered response rules that match on method, path, headers, or body — first match wins",
      "Visual response rules editor in endpoint settings with drag-to-reorder",
      "Rules evaluated in the Rust receiver for low-latency conditional responses",
      "Full SDK, MCP, and API support for managing response rules",
    ],
  },
  {
    version: "0.17.4",
    date: "2026-04-08",
    title: "SEO & Accessibility Improvements",
    track: "web",
    items: [
      "Custom 404 page, OG image optimization (PNG→JPG), and improved sitemap generation",
      "Comprehensive structured data (JSON-LD) and meta tag improvements across all pages",
      "LLMs-full.txt for AI agent discoverability",
    ],
  },
  {
    version: "0.17.3",
    date: "2026-04-06",
    title: "Configurable Limits & Security Hardening",
    track: "web",
    items: [
      "Endpoint creation rate limits, ephemeral caps, and receiver body size now configurable via env vars",
      "Stored XSS regression test suite for endpoint names, mock responses, and request data",
    ],
  },
  {
    version: "0.17.2",
    date: "2026-04-06",
    title: "Teams Module Refactor",
    track: "web",
    items: [
      "Atomic team invite acceptance with member limit enforcement (max 25)",
      "Split teams module into focused sub-modules for better maintainability",
    ],
  },
  {
    version: "0.17.1",
    date: "2026-04-05",
    title: "Consolidated Provider Logic",
    track: "web",
    items: [
      "Unified webhook provider lists, signing, and payload generation via SDK — single source of truth",
      "Added standard-webhooks provider to Send Webhook dialog (fixes drift from SDK/MCP)",
      "Shared mock response validation across endpoint routes using SDK constants",
    ],
  },
  {
    version: "0.17.0",
    date: "2026-04-04",
    title: "Redis-Backed Rate Limiting",
    track: "web",
    items: [
      "Distributed rate limiting via Redis sliding window for all API routes",
      "Receiver notification deduplication backed by Redis",
      "Graceful fallback to in-memory rate limiting when Redis is unavailable",
    ],
  },
  {
    version: "0.16.0",
    date: "2026-04-04",
    title: "Raw Body Fidelity & Search Performance",
    track: "web",
    items: [
      "Raw body storage for non-UTF-8 payloads preserves byte-exact fidelity",
      "Trigram-indexed full-text search across request path, body, and headers",
      "Improved SSE streaming with raw body support",
      "SDK version drift fix and accurate Retry-After headers",
    ],
  },
  {
    version: "0.15.0",
    date: "2026-04-03",
    title: "Notification Webhooks",
    track: "web",
    items: [
      "Configure a notification URL on any endpoint to receive POST alerts when webhooks are captured",
      "Supports Slack, Discord, Microsoft Teams, and any webhook-compatible service",
      "Notification URL management in endpoint settings and via API/SDK/MCP",
      "New docs page for notification webhooks",
    ],
  },
  {
    version: "0.14.1",
    date: "2026-04-02",
    title: "API Key Deletion Confirmation",
    track: "web",
    items: ["Added confirmation dialog before deleting API keys to prevent accidental revocation"],
  },
  {
    version: "0.14.0",
    date: "2026-03-29",
    title: "API Explorer & Rate Limiting",
    track: "web",
    items: [
      "Interactive API explorer at /api-explorer powered by Scalar",
      "OpenAPI 3.1.0 specification at /openapi.yaml",
      "Improved rate limiting with sliding window and informational headers",
      "SDK error messages now include rate limit details and Retry-After hints",
    ],
  },
  {
    version: "0.13.1",
    date: "2026-03-28",
    title: "Pricing Copy Updates",
    track: "web",
    items: [
      "Updated pricing copy across comparison pages and docs",
      "Teams highlighted as Pro-exclusive feature",
    ],
  },
  {
    version: "0.13.0",
    date: "2026-03-28",
    title: "Teams",
    track: "web",
    items: [
      "Create and manage teams with invite-based membership",
      "Share endpoints with team members",
      "Team roles: owner and member with scoped permissions",
      "Endpoint switcher shows personal and team endpoints",
      "Teams documentation page",
    ],
  },
  {
    version: "0.12.1",
    date: "2026-03-27",
    title: "Comparison Pages Expansion",
    track: "web",
    items: [
      "New comparison pages: Hookdeck, localtunnel, RequestBin, Smee",
      "Redesigned Beeceptor, ngrok, and Webhook.site comparison pages",
      "Shared comparison CTA component",
    ],
  },
  {
    version: "0.12.0",
    date: "2026-03-26",
    title: "Request Debugging Tools",
    track: "web",
    items: [
      "Pin requests to keep them visible across endpoint switches",
      "Add notes to captured requests (stored locally)",
      "Side-by-side request diff comparison",
      "Visual request timeline view",
      "Interactive dashboard guide",
      "Dashboard features documentation page",
    ],
  },
  {
    version: "0.11.0",
    date: "2026-03-26",
    title: "Dashboard Improvements",
    track: "web",
    items: [
      "Keyboard shortcuts for dashboard navigation",
      "Collapsible JSON tree viewer for request bodies",
      "JSON to TypeScript type generation",
      "Resizable split pane in request viewer",
      "Richer request list rows with method badges and size",
    ],
  },
  {
    version: "0.10.1",
    date: "2026-03-26",
    title: "Case-Insensitive Slugs",
    track: "web",
    items: [
      "Endpoint slugs are now case-insensitive (e.g. /w/AbC and /w/abc resolve to the same endpoint)",
    ],
  },
  {
    version: "0.10.0",
    date: "2026-03-25",
    title: "Conversion Funnel & Live Preview",
    track: "web",
    items: [
      "Live webhook preview on landing page",
      "Getting started guide for new users",
      "Claim ephemeral endpoints after signing in",
      "Site stats social proof on landing page",
      "Pricing CTA and docs CTA components",
      "Redesigned hero and navigation",
    ],
  },
  {
    version: "0.9.3",
    date: "2026-03-21",
    title: "Docs Expansion",
    track: "web",
    items: [
      "REST API reference documentation page",
      "Plans & limits documentation page",
      "Webhook.site vs webhooks.cc comparison page",
      "Docs navigation restructure and consistency improvements",
    ],
  },
  {
    version: "0.9.2",
    date: "2026-03-20",
    title: "Changelog & Version Display",
    track: "web",
    items: [
      "Public changelog page at /changelog with track filtering",
      "Version display on account page",
      "Deep health check endpoint for AppSignal uptime monitoring",
      "Forward user IP on test webhook sends",
      "Status page link in footer",
    ],
  },
  {
    version: "0.9.1",
    date: "2026-03-20",
    title: "Provider Templates & Mock Response Delay",
    track: "web",
    items: [
      "Add SendGrid, Clerk, Discord, Vercel, GitLab provider templates (12 total)",
      "Configurable response delay for mock responses (0-30s)",
      "Comprehensive analytics tracking for request and endpoint operations",
      "New provider template reference documentation page",
    ],
  },
  {
    version: "0.9.0",
    date: "2026-03-16",
    title: "AppSignal & Next.js 16 Proxy",
    track: "web",
    items: [
      "Replace Sentry with AppSignal for EU data residency compliance",
      "OpenTelemetry tracing pipeline for Rust receiver",
      "Migrate Next.js middleware.ts to proxy.ts (Next.js 16)",
      "Proxy test webhook sends through server-side API route",
    ],
  },
  {
    version: "0.8.0",
    date: "2026-03-10",
    title: "Docs Overhaul",
    track: "web",
    items: [
      "14 new documentation pages with MDX pipeline",
      "Standard Webhooks provider and sendTo method",
      "Dynamic blog system with API publishing",
      "PostHog analytics integration",
      "Receiver file logging with daily rotation",
      "Adjusted tier quotas (guest 25/12hrs, free 50/day, pro 100K/month)",
    ],
  },
  {
    version: "0.7.4",
    date: "2026-02-27",
    title: "SEO & Navigation Refresh",
    track: "web",
    items: ["Refresh site metadata and navigation layout", "Fix sitemap response content"],
  },
  {
    version: "0.7.3",
    date: "2026-02-22",
    title: "Webhook Templates & Retention",
    track: "web",
    items: [
      "Signed webhook templates (Stripe, GitHub, Shopify, Twilio, Slack, Paddle, Linear)",
      "Request retention policy improvements",
      "Homepage comparison section",
    ],
  },
  {
    version: "0.7.2",
    date: "2026-02-17",
    title: "SEO & Search",
    track: "web",
    items: [
      "Structured data (JSON-LD), FAQ section, breadcrumbs",
      "Add llms.txt for AI discovery",
      "Full-text search across request body, headers, and path",
      "Paginated request history with retention policies",
    ],
  },
  {
    version: "0.7.0",
    date: "2026-02-10",
    title: "Rust Receiver & CLI TUI",
    track: "web",
    items: [
      "Rewrite webhook receiver from Go to Rust (Axum + sqlx + Tokio)",
      "Optimize database with stored procedures (capture_webhook())",
      "Guest live dashboard for unauthenticated users",
      "Strict quota enforcement for all endpoint types",
    ],
  },
  {
    version: "0.6.0",
    date: "2026-02-06",
    title: "Production Hardening",
    track: "web",
    items: [
      "Six phases of production hardening (abuse protection, CSP, rate limiting)",
      "Integration test suite (42 test cases)",
      "SEO metadata, sitemap improvements, crawler exclusions",
    ],
  },
  {
    version: "0.5.0",
    date: "2026-02-05",
    title: "Security & Docs",
    track: "web",
    items: [
      "Security hardening across backend, API routes, and CLI",
      "Floating navbar, sidebar, and docs improvements",
    ],
  },
  {
    version: "0.4.0",
    date: "2026-02-04",
    title: "Public Pages",
    track: "web",
    items: [
      "Installation page with copy-paste commands",
      "Privacy policy and terms of service pages",
      "XML sitemap generation",
    ],
  },
  {
    version: "0.3.0",
    date: "2026-02-02",
    title: "Billing & Polish",
    track: "web",
    items: [
      "Polar.sh subscription management (free/pro tiers)",
      "Request batching and endpoint caching for high-throughput",
      "Dashboard UI improvements (empty states, layout fixes)",
    ],
  },
  {
    version: "0.2.0",
    date: "2026-01-30",
    title: "CI/CD & Code Quality",
    track: "web",
    items: [
      "CI pipeline with lint, typecheck, build, and test stages",
      "Dependabot and CodeQL security scanning",
      "Input validation, CSP, and rate limiting",
    ],
  },
  {
    version: "0.1.0",
    date: "2026-01-28",
    title: "Initial Release",
    track: "web",
    items: [
      "Dashboard with webhook capture and real-time inspection",
      "GitHub and Google OAuth authentication",
      "Basic endpoint CRUD and request viewer",
    ],
  },

  // ─── CLI ────────────────────────────────────────────────────────────
  {
    version: "1.1.3",
    date: "2026-08-11",
    title: "Self-Update Rescue for v0.x Installs",
    track: "cli",
    items: [
      "Releases again include the legacy `whk_<os>_<arch>` archives (with checksums), so `whk update` works from pre-1.0 installs — v0.6.0 users stuck on “no release asset for darwin/arm64” can now update straight to the current version",
      "No binary changes — identical CLI code to 1.1.2",
    ],
  },
  {
    version: "1.1.2",
    date: "2026-05-24",
    title: "Update Command Polish",
    track: "cli",
    items: [
      "`whk update` now displays the current version correctly (was rendering as `vv1.0.0` due to a double `v` prefix)",
      "When the install directory isn't user-writable, `whk update` fails fast with a clear message naming the path and suggesting `sudo whk update` or a user-writable reinstall — instead of the cryptic `Permission denied (os error 13)` after a multi-MB download",
    ],
  },
  {
    version: "1.1.1",
    date: "2026-05-23",
    title: "Dependency Maintenance",
    track: "cli",
    items: [
      "tokio 1.51 → 1.52, rustls-webpki refresh, axum 0.8.9, rand 0.8.6, clap 4.6.1, clap_complete 4.6.5, open 5.3.5 — picks up upstream security fixes",
      "Internal clippy 1.95 cleanups in the TUI event loop and update screen (no behavior change)",
    ],
  },
  {
    version: "1.1.0",
    date: "2026-04-15",
    title: "Signature Verification",
    track: "cli",
    items: [
      "Tunnel forwards X-Signature-Verified, X-Signature-Provider, and X-Signature-Error headers",
      "Listen shows inline verification status (checkmark/cross) per request",
      "Create supports --signing-provider and --signing-secret flags (or WHK_SIGNING_SECRET env var)",
    ],
  },
  {
    version: "1.0.0",
    date: "2026-04-01",
    title: "Rust Rewrite",
    track: "cli",
    items: [
      "Complete rewrite from Go to Rust for faster startup and smaller binaries",
      "Full feature parity: tunnel, listen, auth, endpoints, requests, replay, send, update",
      "Interactive TUI with ratatui (search, endpoint detail, request viewer)",
      "Request search and filtering in TUI",
      "Send webhooks with provider template signing from TUI",
    ],
  },
  {
    version: "0.6.0",
    date: "2026-03-28",
    title: "Teams Support",
    track: "cli",
    items: [
      "Endpoint list shows owned and team-shared endpoints",
      "TeamShare metadata in endpoint responses",
    ],
  },
  {
    version: "0.5.3",
    date: "2026-03-14",
    title: "Tunnel Base Path & TUI Fixes",
    track: "cli",
    items: [
      "Support base path in tunnel target (e.g. whk tunnel 8080/api/webhooks)",
      "Fix TUI tunnel input swallowing shortcut-bound keys",
    ],
  },
  {
    version: "0.5.2",
    date: "2026-03-14",
    title: "Custom Headers",
    track: "cli",
    items: ["Add -H/--header flag for injecting custom headers in tunnel forwarding"],
  },
  {
    version: "0.5.1",
    date: "2026-02-19",
    title: "Replay & Ephemeral",
    track: "cli",
    items: [
      "Add whk replay command to resend captured requests",
      "Add --ephemeral flag for auto-deleting tunnel endpoints",
    ],
  },
  {
    version: "0.5.0",
    date: "2026-02-10",
    title: "TUI Mode",
    track: "cli",
    items: [
      "Interactive TUI with menu, auth, endpoint listing, and request detail views",
      "Real-time SSE subscriptions in TUI",
    ],
  },
  {
    version: "0.4.0",
    date: "2026-02-06",
    title: "Device Auth",
    track: "cli",
    items: [
      "Browser-based device authentication flow",
      "whk update self-update with SHA256 verification",
    ],
  },
  {
    version: "0.3.0",
    date: "2026-02-05",
    title: "Cosign Signing",
    track: "cli",
    items: ["Cosign keyless signing for release binaries"],
  },
  {
    version: "0.2.0",
    date: "2026-02-04",
    title: "Initial Release",
    track: "cli",
    items: [
      "whk tunnel for forwarding webhooks to localhost",
      "whk listen for streaming requests to terminal",
      "whk create, list, delete for endpoint management",
    ],
  },

  // ─── SDK ────────────────────────────────────────────────────────────
  {
    version: "1.9.0",
    date: "2026-06-05",
    title: "4 New Providers — DocuSign, Adyen, PayPal, Plaid",
    track: "sdk",
    items: [
      "Added DocuSign, Adyen, PayPal, and Plaid templates, bringing TEMPLATE_PROVIDERS to 32 named providers",
      "New verifiers: verifyDocuSignSignature, verifyAdyenSignature, and verifyPayPalSignature with PayPal certificate URL validation and RSA-SHA256 verification",
      "New detection helpers: isDocuSignWebhook, isAdyenWebhook, isPayPalWebhook, and isPlaidWebhook; Plaid remains template-only for verification",
    ],
  },
  {
    version: "1.8.0",
    date: "2026-06-02",
    title: "Agent self-registration on-ramp",
    track: "sdk",
    items: [
      "New static WebhooksCC.register helpers let an agent obtain its own credential before it has one: anonymous (with claim code + poll/waitForClaim), verified_email (withEmail + confirmEmailOtp), and identity_assertion (withIdJag)",
      "WebhooksCC.describeRegistration() and client.describe().registration surface the auth.md on-ramp so an unauthenticated agent can discover how to register",
      "Standalone exports (registerAnonymous, registerWithEmail, confirmEmailOtp, registerWithIdJag, pollClaim, waitForClaim) plus an AgentRegisterError carrying the auth.md error code",
    ],
  },
  {
    version: "1.7.0",
    date: "2026-05-31",
    title: "7 New Providers — Square, HubSpot, Mailgun, Calendly, Mux, Sentry, Bitbucket",
    track: "sdk",
    items: [
      "Added Square, HubSpot, Mailgun, Calendly, Mux, Sentry, and Bitbucket to templates, detection, and verification — the catalog now covers 28 named providers",
      "New verifiers: verifySquareSignature, verifyHubSpotSignature, verifyMailgunSignature, verifyCalendlySignature, verifyMuxSignature, verifySentrySignature, verifyBitbucketSignature",
      "New detection helpers: isSquareWebhook, isHubSpotWebhook, isMailgunWebhook, isCalendlyWebhook, isMuxWebhook, isSentryWebhook, isBitbucketWebhook",
      "VerifySignatureOptions gains an optional method field; Square and HubSpot verification require the request url (HubSpot also uses the method and rejects timestamps older than 5 minutes)",
      "Bitbucket is detected on x-event-key before Intercom to avoid the shared x-hub-signature collision (Bitbucket sha256=, Intercom sha1=)",
    ],
  },
  {
    version: "1.6.0",
    date: "2026-05-31",
    title: "7 New Providers",
    track: "sdk",
    items: [
      "Added Meta (WhatsApp/Messenger/Instagram), Lemon Squeezy, Coinbase Commerce, Razorpay, Cal.com, Intercom, and Telegram to templates, detection, and verification",
      "New verifiers: verifyMetaSignature, verifyLemonSqueezySignature, verifyCoinbaseCommerceSignature, verifyRazorpaySignature, verifyCalSignature, verifyIntercomSignature, verifyTelegramSignature",
      "New detection helpers: isMetaWebhook, isLemonSqueezyWebhook, isCoinbaseCommerceWebhook, isRazorpayWebhook, isCalWebhook, isIntercomWebhook, isTelegramWebhook",
      "Meta is detected by body shape (ordered before GitHub); Intercom (sha1=) is disambiguated from GitHub's x-hub-signature-256 and Bitbucket's sha256=",
    ],
  },
  {
    version: "1.5.0",
    date: "2026-05-15",
    title: "Typeform Provider & Webhook Auto-Detect",
    track: "sdk",
    items: [
      "Typeform provider templates (form_response, partial_response, payment) and verifyTypeformSignature",
      "detectWebhookInfo() and detectWebhookProvider() helpers for provider auto-detection from headers and body",
      "DetectedWebhookInfo type and isTypeformWebhook detection helper",
    ],
  },
  {
    version: "1.4.0",
    date: "2026-04-15",
    title: "Signature Verification Matchers",
    track: "sdk",
    items: [
      "matchVerified() and matchUnverified() matchers for signature verification assertions",
      "signatureVerified, signatureError, and signingProvider fields on Request and Endpoint types",
    ],
  },
  {
    version: "1.3.0",
    date: "2026-04-10",
    title: "Response Rules & Provider Consolidation",
    track: "sdk",
    items: [
      "ResponseRule and ResponseRuleCondition types for conditional mock responses",
      "validateResponseRules() and validation constants exported for shared use",
      "TEMPLATE_PROVIDERS, VERIFY_PROVIDERS, and buildTemplateSendOptions exports — single source of truth for provider logic",
      "Notification URL support in create/update endpoint options",
      "Raw body replay with byte-exact fidelity (base64-decoded bodyRaw)",
    ],
  },
  {
    version: "1.2.1",
    date: "2026-03-29",
    title: "Rate Limit Metadata",
    track: "sdk",
    items: [
      "RateLimitError now includes limit, remaining, and reset fields",
      "New RateLimitMeta type export",
    ],
  },
  {
    version: "1.2.0",
    date: "2026-03-28",
    title: "Teams Support",
    track: "sdk",
    items: [
      "TeamShare type for endpoint team metadata",
      "Endpoint type includes sharedWith and fromTeam fields",
    ],
  },
  {
    version: "1.1.0",
    date: "2026-03-20",
    title: "New Provider Templates",
    track: "sdk",
    items: [
      "Add SendGrid, Clerk, Discord, Vercel, GitLab provider templates",
      "Detection helpers: isSendGridWebhook, isClerkWebhook, isVercelWebhook, isGitLabWebhook",
      "Signature verification: verifyClerkSignature, verifyVercelSignature, verifyGitLabSignature",
      "Mock response delay field",
    ],
  },
  {
    version: "1.0.1",
    date: "2026-03-14",
    title: "Proxy & Delay",
    track: "sdk",
    items: ["Mock response delay field support", "Minor type and documentation fixes"],
  },
  {
    version: "1.0.0",
    date: "2026-03-10",
    title: "Stable API",
    track: "sdk",
    items: [
      "WebhookFlowBuilder for multi-step test scenarios",
      "Request export (JSON, HAR) and clear methods",
      "Full-text search and count queries",
    ],
  },
  {
    version: "0.6.0",
    date: "2026-03-08",
    title: "Build Request & Fixes",
    track: "sdk",
    items: [
      "buildRequest method for constructing signed webhook requests",
      "Fix raw secret detection for Standard Webhooks",
      "Request diffing (diffRequests)",
    ],
  },
  {
    version: "0.5.0",
    date: "2026-03-08",
    title: "Standard Webhooks & sendTo",
    track: "sdk",
    items: [
      "Standard Webhooks provider and sendTo method",
      "matchContentType, matchQueryParam, matchBodySubset matchers",
      "Provider template sending with signed headers",
    ],
  },
  {
    version: "0.4.0",
    date: "2026-02-22",
    title: "Signature Verification",
    track: "sdk",
    items: [
      "verifySignature for Stripe, GitHub, Shopify, Twilio, Slack, Paddle, Linear",
      "Webhook templates with realistic payloads",
    ],
  },
  {
    version: "0.3.0",
    date: "2026-02-14",
    title: "SSE Streaming",
    track: "sdk",
    items: [
      "subscribe() SSE async iterator for real-time streaming",
      "describe() introspection for AI agents",
    ],
  },
  {
    version: "0.2.0",
    date: "2026-02-06",
    title: "Matchers & Helpers",
    track: "sdk",
    items: [
      "Composable request matchers (matchMethod, matchHeader, matchBodyPath, matchAll, matchAny)",
      "Provider detection helpers (isStripeWebhook, isGitHubWebhook, etc.)",
      "parseJsonBody, parseFormBody, extractJsonField helpers",
    ],
  },
  {
    version: "0.1.0",
    date: "2026-02-05",
    title: "Initial Release",
    track: "sdk",
    items: [
      "Endpoint CRUD (create, get, list, delete, update)",
      "Request list, waitFor with timeout and polling",
      "Replay captured requests to any URL",
      "Human-readable duration strings (30s, 5m)",
    ],
  },

  // ─── MCP ────────────────────────────────────────────────────────────
  {
    version: "1.7.0",
    date: "2026-06-05",
    title: "4 New Providers",
    track: "mcp",
    items: [
      "DocuSign, Adyen, PayPal, and Plaid are available in provider template tools through the SDK catalog; verify_signature now exposes DocuSign, Adyen, and PayPal while keeping Plaid template-only",
    ],
  },
  {
    version: "1.6.0",
    date: "2026-06-02",
    title: "Agent self-registration on-ramp",
    track: "mcp",
    items: [
      "New unauthenticated tools — how_to_register, register_agent, and check_claim — let an agent with no API key learn the auth.md flows and drive the anonymous register + claim handshake",
      "The MCP server now boots without WHK_API_KEY, exposing only the registration on-ramp so an agent can obtain a credential instead of failing to start",
      "describe now includes the registration on-ramp block from the SDK",
    ],
  },
  {
    version: "1.5.0",
    date: "2026-05-31",
    title: "7 New Providers — Square, HubSpot, Mailgun, Calendly, Mux, Sentry, Bitbucket",
    track: "mcp",
    items: [
      "Square, HubSpot, Mailgun, Calendly, Mux, Sentry, and Bitbucket are now available in send_webhook, send_to, preview_webhook, list_provider_templates, and verify_signature — wired automatically through the SDK provider lists, bringing the catalog to 28 named providers",
    ],
  },
  {
    version: "1.4.2",
    date: "2026-05-31",
    title: "7 New Providers",
    track: "mcp",
    items: [
      "Meta, Lemon Squeezy, Coinbase Commerce, Razorpay, Cal.com, Intercom, and Telegram are now available in send_webhook, send_to, preview_webhook, list_provider_templates, and verify_signature — wired automatically through the SDK provider lists",
    ],
  },
  {
    version: "1.4.1",
    date: "2026-05-23",
    title: "zod 4 Upgrade",
    track: "mcp",
    items: [
      "Upgrades the zod dependency from 3.x to 4.x with the matching tool-schema adaptation in src/tools.ts",
    ],
  },
  {
    version: "1.4.0",
    date: "2026-05-15",
    title: "Typeform Provider Support",
    track: "mcp",
    items: [
      "Typeform exposed in list_provider_templates with templates, default event, and signature metadata",
      "Typeform usable in create_endpoint and update_endpoint signing config",
    ],
  },
  {
    version: "1.3.0",
    date: "2026-04-15",
    title: "Signature Verification Tools",
    track: "mcp",
    items: [
      "Signing config (provider + secret) on create_endpoint and update_endpoint",
      "verify_signature tool returns stored server-side results with skipped detection",
      "Discord publicKey support for Ed25519 verification",
    ],
  },
  {
    version: "1.2.0",
    date: "2026-04-10",
    title: "Response Rules & Notifications",
    track: "mcp",
    items: [
      "Response rules support in create_endpoint and update_endpoint tools",
      "Notification URL parameter for endpoint creation and updates",
      "Provider lists imported from SDK — single source of truth",
    ],
  },
  {
    version: "1.1.0",
    date: "2026-03-20",
    title: "New Provider Templates",
    track: "mcp",
    items: [
      "Add SendGrid, Clerk, Discord, Vercel, GitLab to template and verify providers",
      "Mock response delay support",
    ],
  },
  {
    version: "1.0.1",
    date: "2026-03-14",
    title: "Delay & Fixes",
    track: "mcp",
    items: ["Mock response delay support in update_endpoint tool", "Minor schema fixes"],
  },
  {
    version: "1.0.0",
    date: "2026-03-10",
    title: "Stable API",
    track: "mcp",
    items: [
      "Standard Webhooks provider support",
      "Batch endpoint create/delete tools",
      "Request export, search, and clear tools",
      "Setup commands for Cursor, VS Code, Windsurf, Claude Desktop, Codex",
    ],
  },
  {
    version: "0.3.0",
    date: "2026-03-08",
    title: "Signature & Templates",
    track: "mcp",
    items: [
      "verify_signature tool for 9 providers",
      "send_webhook with provider template signing",
      "compare_requests and extract_from_request tools",
    ],
  },
  {
    version: "0.2.0",
    date: "2026-02-22",
    title: "Webhook Templates",
    track: "mcp",
    items: ["Provider template support in send_webhook", "list_provider_templates tool"],
  },
  {
    version: "0.1.0",
    date: "2026-02-14",
    title: "Initial Release",
    track: "mcp",
    items: [
      "11 tools: create/list/get/update/delete endpoints, list/get requests, send/wait/replay, describe",
      "stdio transport via @modelcontextprotocol/sdk",
      "Setup CLI for Cursor, VS Code, Windsurf, Claude Desktop",
    ],
  },
];
